#######################################################
#                                                     #
#                  >> NoTNTPlus <<                    #
#                                                     #
#              Plugin created By Pulsi_               #
#                                                     #
#             For help join my discord!               #
#           https://discord.gg/XMtFZvwXZG             #
#                                                     #
#                                                     #
#######################################################

#Receive the update message if available
update_checker: true


#######################################################
#                     MANAGERS                        #
#######################################################

place:
  #Enable/Disable the tnt place -> Permission: notntplus.place.tnt
  disable_tnt_place: true

  #Enable/Disable the tnt place -> Permission: notntplus.place.tntminecart
  disable_tntminecart_place: true

  #Enable/Disable the tnt place -> Permission: notntplus.place.creeperegg
  disable_creeperegg_place: true

  #Enable/Disable the tnt place -> Permission: notntplus.place.bed
  disable_bed_place: true


interact:
  #Enable/Disable the tnt interact -> Permission: notntplus.interact.tnt
  disable_tnt_interact: true

  #Enable/Disable the tnt interact -> Permission: notntplus.interact.bed
  disable_bed_interact: true


click_remove:
  #Remove the TNT which a player is trying to turn on
  remove_the_clicked_tnt: true

  #Remove the TNT which a player is trying to turn on
  remove_the_clicked_bed: true


noDamage:
  #Disable the Explosions Damage
  disable_explosions_damage: true


explosions:

  #Disable TNT explosion
  disable_tnt_explosion: true

  #Disable TNTMinecart explosion
  disable_tntminecart_explosion: true

  #Disable Creeper explosion
  disable_creeper_explosion: true

  #Disable Bed explosion
  disable_bed_explosion: true


pickup:

  #Disable TNT Pickup -> Permission: notntplus.pickup.tnt
  disable_tnt_pickup: true

  #Disable TNT Pickup -> Permission: notntplus.pickup.tntminecart
  disable_tntminecart_pickup: true

  #Disable TNT Pickup -> Permission: notntplus.pickup.creeperegg
  disable_creeperegg_pickup: true

  #Disable TNT Pickup -> Permission: notntplus.pickup.bed
  disable_bed_pickup: true