#######################################################
#                                                     #
#                  >> NoTNTPlus <<                    #
#                                                     #
#              Plugin created By Pulsi_               #
#                                                     #
#             For help join my discord!               #
#           https://discord.gg/XMtFZvwXZG             #
#                                                     #
#                                                     #
#######################################################

#Enable/Disable the tnt place -> Permission: notntplus.place
disable_tnt_place: true

#Enable/Disable the tnt interact -> Permission: notntplus.interact
disable_tnt_interact: true

#Remove the TNT which a player is trying to turn on
remove_the_clicked_tnt: true

#Disable TNT Explosions
disable_tnt_explosion: true

#Disable TNT Pickup -> Permission: notntplus.pickup
disable_tnt_pickup: true

#######################################################
#                  TNT PLACE MESSAGES                 #
#######################################################

#The message sent to the player if he try to place TNT
place_send_message: true
place_message: "&8[&a&lNo&c&lTNT&b&l+&8] &cYeah it's fun to randomly place tnt around the map."

#The message sent to console when a player try to place TNT
place_send_report: true
place_report_message: "&8[&a&lNo&c&lTNT&b&l+&8] &b&l%player% &c&lIs trying to place TNT!!"


#######################################################
#                TNT INTERACT MESSAGES                #
#######################################################

#The interact message sent to the player
interact_send_message: true
interact_message: "&8[&a&lNo&c&lTNT&b&l+&8] &cNice try!"

#The interact report sent to the console
interact_send_report: true
interact_report_message: "&8[&a&lNo&c&lTNT&b&l+&8] &b&l%player% &c&lIs trying to power on a TNT!!"