#######################################################
#                                                     #
#                  >> NoTNTPlus <<                    #
#                                                     #
#              Plugin created By Pulsi_               #
#                                                     #
#             For help join my discord!               #
#           https://discord.gg/XMtFZvwXZG             #
#                                                     #
#                                                     #
#######################################################

#Receive the update message if available
update_checker: true

#Enable/Disable the tnt place -> Permission: notntplus.place
disable_tnt_place: true

#Enable/Disable the tnt interact -> Permission: notntplus.interact
disable_tnt_interact: true

#Remove the TNT which a player is trying to turn on
remove_the_clicked_tnt: true

#Disable the TNT explosion damage
disable_tnt_damage: true


#######################################################
#                     EXPLOSIONS                      #
#######################################################

#Disable TNT explosion
disable_tnt_explosion: true

#Disable Creeper explosion
disable_creeper_explosion: true

#Disable TNTMinecart explosion
disable_tntminecart_explosion: true


#######################################################
#                       PICKUP                        #
#######################################################

#Disable TNT Pickup -> Permission: notntplus.pickup.tnt
disable_tnt_pickup: true

#Disable TNT Pickup -> Permission: notntplus.pickup.tntminecart
disable_tntminecart_pickup: true

#Disable TNT Pickup -> Permission: notntplus.pickup.creeperegg
disable_creeperegg_pickup: true